### PR TITLE
Add nightly flatpak builder generator

### PR DESCRIPTION
**Pull request by grillo-delmal**
~~Can't test this on my fork yet, but should work~~
Forgot to mention that this is working XDD
Tested it here https://github.com/grillo-delmal/nijiexpose-dummy/actions/runs/10462682288
Results here https://github.com/grillo-delmal/nijiexpose-dummy/releases/tag/nightly

### CODE REVIEW

**Comment by grillo-delmal** [comment]
Just commenting to mention that this works :3

**Comment by seagetch** [comment]
Could you consider to make another build schedule than "nightly"?
I mind if flatpak deployment consumes all my available CPU resource on github. hopefully this flatpak build is executed weekly.
Maybe same for nijigenerate.
(Once separated, we can adjust the schedule later.)

**Comment by grillo-delmal** [comment]
Sure ^^ ill separate flatpak generation to another file and decreace the frequency :+1:

**Comment by grillo-delmal** [comment]
done :+1:

**Pull request merged**
